#spring:
#  datasource:
#    dynamic:
#      enabled: true
#      strict: true
#      primary: "cds-mysql"

---
spring:
  config:
    activate:
      on-profile: suyh

  datasource:
    url: jdbc:mysql://192.168.8.143:3306/suyh_cdap_2_cds?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: suyh_cdap_2_cds
    password: suyh_cdap_2_cds
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver





